### PR TITLE
Added event to intercept the creation of absolute paths

### PR DESCRIPTION
**Pull request by DarthAffe**
This should address #82 
@SpoinkyNL could you take a look at this and check if that would work for you?

### CODE REVIEW

**Comment by SpoinkyNL** [comment]
This is what I came up with but it didn't work:

```cs
private void ResolveCorsairPath(object sender, ResolvePathEventArgs e)
{
    if (sender is CorsairRGBDevice<CorsairRGBDeviceInfo>)
    {
        // stuff
    }
}
```

So I opted for the following, I had hoped to avoid a string-based check since things can change quite easily but I don't think this'll break in the future.
```cs
private void ResolveCorsairPath(object sender, ResolvePathEventArgs e)
{
    if (e.RelativePart.Contains("Layouts\\Corsair"))
    {
        // Strip Corsair from the path
        var strippedRelativePart = e.RelativePart.Replace("\\Corsair", "");
        // Start from the plugin directory
        e.FinalPath = Path.Combine(PluginInfo.Directory.FullName, strippedRelativePart, e.FileName);
    }
}
```

Thoughts? I'd say this works for me.

**Comment by DarthAffe** [comment]
I'd go for the first way but change the check to ICorsairRGBDevice - it won't match like this since the generic part isn't the base class. (checking against CorsairRGBDevice<> might work too, but that's what the interface is for :p)

**Comment by SpoinkyNL** [comment]
Went with this like you suggested but I wrapped it into a extension method, since I'll be reusing this
```cs
public static bool IsGenericType(this Type type, Type genericType)
{
    if (type == null)
        return false;
   
    return type.BaseType?.GetGenericTypeDefinition() == genericType;
}
```

So it turns out as:
```cs
if (sender.GetType().IsGenericType(typeof(CorsairRGBDevice<>)))
{
    // Start from the plugin directory
    e.FinalPath = Path.Combine(PluginInfo.Directory.FullName, e.RelativePart, e.FileName);
}
```

Happy with this approach so if you are too, we can merge this ^^

**Comment by DarthAffe** [comment]
Doesn't look that bad like this but I still wonder why i didn't include a public interface ~ I think I'll add one which should make that even easier.

**Pull request merged**
