### PR TITLE
Check RGBDeviceType.All in RGBSurface.GetDevices

### PR DESCRIPTION
**Pull request by Sander0542**
Add a check for the RGBDeviceType.All in the RGBSurface.GetDevices function

### CODE REVIEW

**Comment by DarthAffe** [comment]
That's a really good point. I never thought about that kind of usage.

**Comment by Sander0542** [comment]
I was trying to load all my devices in a listview, but it didnt work and took a look at the code. I am happy to help with this. Btw, why is there nog nuget package for Devices.Msi?

**Comment by DarthAffe** [comment]
Msi isn't completely implemented until now.

**Comment by Sander0542** [comment]
Oh okay, Thanks! Can you make a Nuget Package with all the other packages in it like there was on the old URL, please?

**Pull request merged**
