### PR TITLE
Sdk/logitech

### PR DESCRIPTION
**Pull request by DarthAffe**
Fixing the G Pro mouse, which starts at zone 1 for whatever reason

### CODE REVIEW

**Comment by DarthAffe** [comment]
@diogotr7 Could you run a quick test with this to make sure it doesn't brake your changes? I don't have access to a logitech zone device :(

**Comment by diogotr7** [comment]
It detected and addresses my G900 successfully. It did however bring up a timeout issue i'd like to fix with wireless detection. It only happens about half the time i detect, i'll try playing with timeout values to see if i can remedy it.

**Comment by diogotr7** [comment]
Adjusting the timeout does not help. The issue is caused by LGS being open in my case. Might have to retry the scan until we get more useful info.

**Comment by diogotr7** [comment]
I implemented a simple retry mechanism that seems to fix it. I couldn't make it fail after trying a few dozen times.

**Comment by diogotr7** [comment]
I've pushed this retry mechanism [here](https://github.com/diogotr7/RGB.NET/commit/4d0f8f40f99fa111573165a6c3dfd9fd1e271359)

Should I make a separate PR to dev with this code?

**Comment by DarthAffe** [comment]
do you have permissions to merge it into this pr? if so just do that and we merge everything together.

**Pull request merged**
